version:    0.1.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

artifacts:
- path: bin\Debug
  name: d2mm-0.1
  
install:
- git submodule update --init --recursive